### PR TITLE
Quality. What does it even mean?

### PR DESCRIPTION
**Pull request by pkananen**

### CODE REVIEW

**Comment by joelturnbull** [comment]
This is like a movie with a totally ambiguous ending that makes me think about it for a week after I see it. More questions than answers. It's good, It'd be awesome if people started commenting on this.

Here's an image.

quality

**Comment by cdmwebs** [comment]
Do we give the images attribution, @joelturnbull?

On Mon, Nov 4, 2013 at 8:43 AM, Joel Turnbull notifications@github.comwrote:

> This is like a movie with a totally ambiguous ending that makes me think
> about it for a week after I see it. More questions than answers. It's good,
> It'd be awesome if people started commenting on this.
> 
> Here's an image.
> 
> [image: quality]https://f.cloud.github.com/assets/89899/1464894/73bf2428-4556-11e3-9d44-0e222595901c.jpg
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/gaslight/posts/pull/51#issuecomment-27685261
> .

## 

Chris Moore | Gaslight
m: 513.201.RUBY (7829)
chrism@gaslight.co
http://gaslight.co

**Comment by pkananen** [comment]
We should probably add a few references to the book.

**Comment by joelturnbull** [comment]
@cdmwebs nah it'll be allright ( I guess we probably should start )

**Pull request merged**
