### PR TITLE
Angular on rails

### PR DESCRIPTION
**Pull request by superchris**

### CODE REVIEW

**Comment by cdmwebs** [comment]
I'll add something about uglifier and mangle false.

**Comment by superchris** [comment]
Good idea. Done.

**Comment by superchris** [comment]
Oops, you said I'll not I'd. Duplicate effort for the double win?

**Comment by cdmwebs** [comment]
Great job :metal: :+1: :hamburger:

**Comment by rockwood** [comment]
This looks like a typo:
   (max - 1 + 1) + 1)

Isn't that just (max + 1)?

**Comment by rockwood** [comment]
I think that config for mangling is for rails 4 only. Maybe it's worth mentioning

**Comment by cdmwebs** [comment]
@rockwood updated.

**Pull request merged**
