### PR TITLE
Beginner's Mind

### PR DESCRIPTION
**Pull request by cdmwebs**
@joelturnbull ok, seriously this time.

Wrong branch.

### CODE REVIEW

**Comment by joelturnbull** [comment]
Yes. Cool concept. Let me take a look tonight after meditation ;)

**Comment by joelturnbull** [comment]
shoshinx

**Comment by cdmwebs** [comment]
Was ist das?

**Comment by joelturnbull** [comment]
Want to ship it? @cdmwebs

**Comment by cdmwebs** [comment]
Shipping!

**Pull request merged**
