### PR TITLE
Gridlockd

### PR DESCRIPTION
**Pull request by joelturnbull**
article about the lumbees

### CODE REVIEW

**Comment by cdmwebs** [comment]
You should rebase ;)

**Comment by joelturnbull** [comment]
heh, github is always making a fool out of me ;)

**Comment by cdmwebs** [comment]
Git is hard. Good post. It's more story than technical.

**Comment by cdmwebs** [comment]
Also, wasn't that a Tupac movie?

edit: [yep](http://www.imdb.com/title/tt0119225/)

**Comment by joelturnbull** [comment]
Didn't see it ;)

**Comment by cdmwebs** [comment]
Ah, that's why. You asked to merge to master. Imma close this one and open a new one.

**Comment by joelturnbull** [comment]
Aw snap I did didn't I?

**Pull request closed without merging**
