### PR TITLE
Ember autosaving inline

### PR DESCRIPTION
**Pull request by cdmwebs**
This is @mitchlloyd's post with the coffeescript inline. Just trying this vs. gist. Comments encouraged.

### CODE REVIEW

**Comment by mitchlloyd** [comment]
Seems like a good way to go if the Gists don't work on mobile and if the GHFM looks sweet on Tumblr..

**Comment by joelturnbull** [comment]
Looks awesome. Doesn't translate to Tumblr at all.

My idea: Forget markdown on Tumblr. We copy the generated HTML from here into Tumblr instead of the Markdown. I already  applied a link to Github's GFM stylesheet in our tumblr layout. It doesn't look the same, but it is approaching something similar within our current layout. The syntax highlighting is good. Then maybe look at something besides Tumblr...

I put another draft of this article in Tumblr that you guys can preview.

**Comment by cdmwebs** [comment]
I had a similar idea. Github puts a bunch of noisy markup in there for
anchor links, etc. I wrote a gem called markyboot last year that outputs
clean HTML from gfm. I tried it this weekend and it worked pretty well.
I'll show you what I tried today too.

On Monday, June 17, 2013, Joel Turnbull wrote:

> Looks awesome. Doesn't translate to Tumblr at all.
> 
> My idea: Forget markdown on Tumblr. We copy the generated HTML from here
> into Tumblr instead of the Markdown. I already applied a link to Github's
> GFM stylesheet in our tumblr layout. It doesn't look the same, but it is
> approaching something similar within our current layout. The syntax
> highlighting is good. Then maybe look at something besides Tumblr...
> 
> I put another draft of this article in Tumblr that you guys can preview.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/gaslight/posts/pull/12#issuecomment-19526346
> .

## 

Chris Moore | Gaslight
m: 513.201.RUBY (7829)
chrism@gaslight.co
http://gaslight.co

**Comment by mitchlloyd** [comment]
One thing I really like about the Gists for a post with a lot of code is
that is it easy to version, update, and have others contribute.

**Comment by cdmwebs** [comment]
I've never seen that happen in real life, but couldn't we do the same using
the code inline?

Not saying it isn't valuable, just a question.

On Mon, Jun 17, 2013 at 9:45 AM, Mitch Lloyd notifications@github.comwrote:

> One thing I really like about the Gists for a post with a lot of code is
> that is it easy to version, update, and have others contribute.
> 
> On Mon, Jun 17, 2013 at 7:29 AM, Chris Moore notifications@github.comwrote:
> 
> > I had a similar idea. Github puts a bunch of noisy markup in there for
> > anchor links, etc. I wrote a gem called markyboot last year that outputs
> > clean HTML from gfm. I tried it this weekend and it worked pretty well.
> > I'll show you what I tried today too.
> > 
> > On Monday, June 17, 2013, Joel Turnbull wrote:
> > 
> > > Looks awesome. Doesn't translate to Tumblr at all.
> > > 
> > > My idea: Forget markdown on Tumblr. We copy the generated HTML from
> > > here
> > > into Tumblr instead of the Markdown. I already applied a link to
> > > Github's
> > > GFM stylesheet in our tumblr layout. It doesn't look the same, but it
> > > is
> > > approaching something similar within our current layout. The syntax
> > > highlighting is good. Then maybe look at something besides Tumblr...
> > > 
> > > I put another draft of this article in Tumblr that you guys can
> > > preview.
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub<
> > > https://github.com/gaslight/posts/pull/12#issuecomment-19526346>
> > > .
> > 
> > ## 
> > 
> > Chris Moore | Gaslight
> > m: 513.201.RUBY (7829)
> > chrism@gaslight.co
> > http://gaslight.co
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/gaslight/posts/pull/12#issuecomment-19539348>
> > .
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/gaslight/posts/pull/12#issuecomment-19545648
> .

## 

Chris Moore | Gaslight
m: 513.201.RUBY (7829)
chrism@gaslight.co
http://gaslight.co

**Pull request merged**
