### PR TITLE
Meeting people

### PR DESCRIPTION
**Pull request by dougalcorn**
I wrote this article after a conversation I had with Joe Herbers. I'm not sure if this really has legs or not. It definitely needs some editing and review. In fact, it may need to be re-written. I just wanted to get it written and checked in.

### CODE REVIEW

**Comment by dougalcorn** [comment]
I was still hitched. That's why michael's name got on this commit.

**Comment by superchris** [comment]
I like it!

**Comment by cdmwebs** [comment]
Good stuff, @dougalcorn. You should run it through http://hemingwayapp.com/ and see what it says.

**Comment by joelturnbull** [comment]
This is cool Doug. The most interesting thing about this article to me is that you consider yourself an introvert. I feel like a lot of us do. But what does that mean? 

Susan Cain, the author of "Quiet" spoke here recently and she had some interesting things to say about it, and specifically about how people work. I think there's a whole article to be written about this introversion/extroversion dichotomy, especially in our little world of software development.

**Comment by dougalcorn** [comment]
Do you think I need to write more about that here? If I were to summarize
the article I might do so in two points:
- Many of us don't find meeting new people easy
- Almost none of us can remember names without a lot of help

As I re-read the article, I'm not sure both points are made. If you feel
like it's ready to ship, then go ahead. If you want me to re-work the
beginning of the article, I will.

On Tue, Aug 20, 2013 at 1:00 AM, Joel Turnbull notifications@github.comwrote:

> This is cool Doug. The most interesting thing about this article to me is
> that you consider yourself an introvert. I feel like a lot of us do. But
> what does that mean?
> 
> Susan Cain, the author of "Quiet" spoke here recently and she had some
> interesting things to say about it, and specifically about how people work.
> I think there's a whole article to be written about this
> introversion/extroversion dichotomy, especially in our little world of
> software development.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/gaslight/posts/pull/41#issuecomment-22922739
> .

## 

Doug Alcorn
(513) 295-2844

**Pull request merged**
