### PR TITLE
How we trello

### PR DESCRIPTION
**Pull request by mguterl**
Check it out @joelturnbull @dougalcorn @pkananen

### CODE REVIEW

**Comment by joelturnbull** [comment]
Good stuff @mguterl. I made some edits and moved it into the active admin for the blog. I'm not sure what's up with the formatting of the ul stuff at the top, but I fixed it up on that side. It's set to launch at 10AM today. We can continue to iterate on it.

**Comment by dougalcorn** [comment]
I think this is good work and I'm glad this is getting written. I'm not sure if this topic is in scope for this article, but there's not much discussion about using a secondary board as the planning board.

**Comment by mguterl** [comment]
@joelturnbull - Thanks for the edits. You definitely helped clarify a few of the parts that felt clumsy to me.

@dougalcorn - We haven't been doing a great job with the planning board. At this point it's mostly being used to keep the icebox out of our main board to help us focus.

**Comment by pkananen** [comment]
The planning board situation really is reflective of the fact that next priorities usually fall out of current work and end up directly on the work board. More and more, we realize that the icebox = YAGNI. —
Peter Kananen
@pkananen
616-617-6269

**Comment by dougalcorn** [comment]
@pkananen do you think that's true for knovation as well? We've not been using trello long enough to see how that will work, but I like the concept. Marci is able to do long-range or high-level release planning not on our development board. Maybe we don't have enough successful experience to talk about it yet.

**Comment by joelturnbull** [comment]
this is rediculous but I need a place to serve an image for now
gaslight_banner

**Pull request merged**
